//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmerEntities : DbContext
    {
        public FilmerEntities()
            : base("name=FilmerEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CinemaLocation> CinemaLocations { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberViewing> MemberViewings { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<Viewing> Viewings { get; set; }
        public virtual DbSet<accesstoken> accesstokens { get; set; }
        public virtual DbSet<MovieApi> MovieApis { get; set; }
    }
}
